Insert into FUNZIONE
   (ID_FUNZIONE, DESCRIZIONE, URL, FLG_LINKABLE, VERSIONE, UTENTE_INSERIMENTO, DATA_INSERIMENTO, UTENTE_AGGIORNAMENTO, DATA_AGGIORNAMENTO)
 Values
   (34, 'Dettaglio utente', '/private/admin/enti/dettaglio/dettaglioUtente', '0', 0, 'ADMIN', TO_DATE('04/14/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', TO_DATE('04/14/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));

Insert into FUNZIONE
   (ID_FUNZIONE, DESCRIZIONE, URL, FLG_LINKABLE, VERSIONE, UTENTE_INSERIMENTO, DATA_INSERIMENTO, UTENTE_AGGIORNAMENTO, DATA_AGGIORNAMENTO)
 Values
   (35, 'Modifica utente', '/private/admin/enti/dettaglio/modificaUtente', '0', 0, 'ADMIN', TO_DATE('04/14/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', TO_DATE('04/14/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
